# Generated by Django 4.2.1 on 2023-05-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocJsonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_file', models.FileField(null=True, upload_to='files/', verbose_name='JSON-файл')),
            ],
            options={
                'verbose_name': 'JSON-файл',
                'verbose_name_plural': 'JSON-файлы',
            },
        ),
        migrations.CreateModel(
            name='ListJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('date', models.DateTimeField(verbose_name='Дата/Время')),
            ],
            options={
                'verbose_name': 'База из JSON',
                'verbose_name_plural': 'Базы из JSON',
            },
        ),
    ]
